CREATE SEQUENCE DB2USER.PTRWLG_ACC_HOST_HISTORY_ID;
CREATE TABLE DB2INST1.PTRWLG_ACCOUNT_HOST_HISTORY (
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
ACCOUNT_OUTSTANDING DECIMAL(14,2),
USER_CODE_3_ID BIGINT,
USER_CODE_3_SEGMENT_ID BIGINT,
BEHAVIOUR_SCORE BIGINT,
BEHAVIOUR_SCORE_GROUP_ID BIGINT,
BEHAVIOUR_SEGMENT_SCORE_ID BIGINT,
B_SEGMENT_SCORE_GROUP_ID BIGINT,
BILLING_CYCLE_ID BIGINT,
BLOCK_CODE_ID BIGINT,
DAYS_IN_ARREARS BIGINT,
MONTHS_IN_ARREARS BIGINT,
DAYS_SINCE_LAST_PAYMENT BIGINT,
DAYS_SINCE_OPENING BIGINT,
PRODUCT_TYPE_CATEGORY_ID BIGINT,
PRODUCT_TYPE_LEVEL_ID BIGINT,
DEBT_RECOVERY_STATUS BIGINT
);
